name: React robots
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: cd react_robots
      - run: npm install
      - run: npm run build
      - run: echo "A first hello!"
  test: 
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: cd react_robots
      - run: npm install
      - run: npm run build
      - run: echo "testing stuff"
      - run: npm test
